---
name: Integration tests

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: 0 0 * * *

jobs:
  generate_versions:
    runs-on: ubuntu-24.04
    outputs:
      versions: ${{ steps.generate-versions.outputs.versions }}
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v4
    - name: Install dependencies
      run: uv pip install --system -r requirements.test
    - name: Generate versions
      id: generate-versions
      run: |
        python .github/get_versions.py >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-24.04
    needs: [generate_versions]
    strategy:
      matrix:
        ha_version: ${{ fromJSON(needs.generate_versions.outputs.versions) }}
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'
    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: 2.26.1
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v4
    - name: Install dependencies
      run: uv pip install --system -r requirements.test
    - name: Integration tests (${{ matrix.ha_version}})
      run: cd integration_tests && python test_banning_works.py
      env:
        HA_VERSION: ${{ matrix.ha_version}}

  # No real steps, just a meta-step to wait for all test steps
  finish:
    needs: [test]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
