---
name: Unit Testing

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v4
    - name: Install dependencies
      run: uv pip install --system -r requirements.test
    - name: pytest
      run: pytest -vvv
      env:
        PYTHONPATH: .
